### ISSUE TITLE
Pretrained model of wavernn doesn't work?

### ISSUE THREAD

**Issue by nadong1** [wqt2019/tacotron-2_wavernn#2]
你好，

我用你提供的wavernn pretrained model遇到一些问题，
你的checkpoints/biaobei_mol.wavernn/下有两个文件:
latest_weights.pyt和latest_optim.pyt

latest_weights.pyt载入会出现维度错误。
latest_optim.pyt可以载入，可是model.get_step()是0，
我使用你提供的tacotron_output/eval/mel-batch_1_sentence_0.npy做输入，可是得到的输出的wav是噪音

请问你的model该如何使用呢？

**Comment by wqt2019** [comment]
sorry , please re-clone the code, it's ok now

**Comment by nadong1** [comment]
你好，

我重新clone后，仍是碰到一样的问题。
我用https://github.com/fatchord/WaveRNN 上的预训练模型，是可以产生语音的。
可是换成你的预训练模型latest_optim.pyt，却只得到noise。

是不是你的预训练模型有错误呢？还是我的使用方式不对呢？可以请你帮忙确认一下吗？

**Comment by wqt2019** [comment]
latest_weight.pyt,用我提供的model，生成部分和声码器参数是匹配的
